export const getFase = (kelas: string): string => {
  const kelasNum = Number.parseInt(kelas)
  if (kelasNum <= 2) return "A"
  if (kelasNum <= 4) return "B"
  return "C"
}

export const getCapaianPembelajaran = (mataPelajaran: string, fase: string): string => {
  const cpData: Record<string, Record<string, string>> = {
    "IPAS (Ilmu Pengetahuan Alam dan Sosial)": {
      A: "Peserta didik menunjukkan rasa ingin tahu tentang diri dan lingkungan sekitarnya sebagai ciptaan Tuhan Yang Maha Esa. Peserta didik mampu mengajukan pertanyaan untuk memahami berbagai fenomena yang dialaminya. Peserta didik mampu melakukan pengamatan terhadap berbagai benda dan peristiwa di lingkungan sekitar menggunakan panca indera. Peserta didik mampu menyampaikan hasil pengamatannya dan gagasannya dalam berbagai bentuk representasi sederhana.",
      B: "Peserta didik mampu menggunakan keterampilan proses untuk menyelidiki alam sekitar, dan menjelaskan fenomena alam dan sosial berdasarkan hasil pengamatan serta sumber bacaan. Peserta didik mampu menunjukkan kepedulian dan tanggung jawab terhadap alam sekitar serta menerapkan pengetahuannya untuk menyelesaikan masalah dalam kehidupan sehari-hari. Peserta didik mampu menyajikan hasil penyelidikan dalam berbagai bentuk representasi serta mengomunikasikannya secara lisan dan tulisan dengan bantuan teknologi.",
      C: "Peserta didik mampu menggunakan keterampilan proses untuk menyelidiki alam sekitar, dan menjelaskan fenomena alam dan sosial berdasarkan hasil pengamatan serta sumber bacaan. Peserta didik mampu menunjukkan kepedulian dan tanggung jawab terhadap alam sekitar serta menerapkan pengetahuannya untuk menyelesaikan masalah dalam kehidupan sehari-hari. Peserta didik mampu menyajikan hasil penyelidikan dalam berbagai bentuk representasi serta mengomunikasikannya secara lisan dan tulisan dengan bantuan teknologi.",
    },
    "Bahasa Indonesia": {
      A: "Peserta didik mampu menyimak, membaca, memirsa, dan/atau mendengarkan informasi dari teks deskriptif, naratif, ekspositori, dan/atau puisi anak. Peserta didik mampu mengungkapkan gagasan secara lisan, tertulis, dan/atau visual. Peserta didik menunjukkan minat terhadap teks sastra dan nonsastra. Peserta didik mampu menggunakan bahasa Indonesia dengan santun untuk berinteraksi dengan lingkungan sosial di sekitar rumah dan sekolah.",
      B: "Peserta didik mampu menyimak, membaca, memirsa berbagai jenis teks untuk memahami informasi dalam berbagai konteks. Peserta didik mampu menyajikan gagasan secara lisan, tertulis, dan visual untuk berbagai tujuan dan konteks. Peserta didik menunjukkan minat dan kegemaran membaca untuk menambah pengetahuan dan keterampilan serta untuk bersenang-senang. Peserta didik mampu menggunakan bahasa Indonesia dengan santun dalam berbagai konteks dan untuk berbagai tujuan.",
      C: "Peserta didik mampu menyimak, membaca, memirsa berbagai jenis teks untuk memahami informasi dalam berbagai konteks. Peserta didik mampu menyajikan gagasan secara lisan, tertulis, dan visual untuk berbagai tujuan dan konteks. Peserta didik menunjukkan minat dan kegemaran membaca untuk menambah pengetahuan dan keterampilan serta untuk bersenang-senang. Peserta didik mampu menggunakan bahasa Indonesia dengan santun dalam berbagai konteks dan untuk berbagai tujuan.",
    },
    Matematika: {
      A: "Peserta didik dapat menunjukkan pemahaman terhadap bilangan cacah sampai 999, dapat melakukan operasi penjumlahan dan pengurangan bilangan cacah sampai 999, dapat mengenal, menggambarkan, dan membandingkan bangun datar dan bangun ruang, dapat mengukur panjang benda dengan satuan tidak baku dan satuan baku, dapat menentukan posisi benda dalam ruang, dapat mengumpulkan, mencatat, dan menyajikan data sederhana menggunakan turus dan tabel sederhana.",
      B: "Peserta didik dapat menunjukkan pemahaman dan melakukan operasi hitung bilangan cacah sampai 10.000, dapat memahami pecahan sederhana, dapat mengenal, menggambarkan, dan menganalisis sifat-sifat bangun datar dan bangun ruang, dapat melakukan pengukuran panjang, massa, waktu, dan volume dengan satuan baku, dapat menentukan posisi dan perpindahan benda dalam bidang koordinat, dapat mengumpulkan, menyajikan, dan menginterpretasi data dalam bentuk tabel, diagram batang, dan diagram lingkaran sederhana.",
      C: "Peserta didik dapat menunjukkan pemahaman dan melakukan operasi hitung bilangan cacah sampai 1.000.000, dapat memahami dan melakukan operasi hitung pecahan dan desimal, dapat mengenal, menggambarkan, dan menganalisis sifat-sifat bangun datar dan bangun ruang serta transformasi geometri, dapat melakukan pengukuran berbagai besaran dengan satuan baku, dapat menentukan posisi dalam bidang koordinat dan memahami penyajian data, dapat mengumpulkan, menyajikan, dan menginterpretasi data dalam berbagai bentuk representasi.",
    },
    "Pendidikan Pancasila": {
      A: "Peserta didik mampu menunjukkan perilaku sesuai dengan nilai-nilai Pancasila, khususnya nilai ketuhanan, kemanusiaan, dan persatuan dalam lingkungan keluarga dan sekolah. Peserta didik mampu menunjukkan perilaku positif (jujur, disiplin, tanggung jawab, santun, peduli, dan percaya diri) dalam berinteraksi dengan keluarga, teman, dan guru sebagai perwujudan nilai moral Pancasila dan karakter yang mencerminkan karakter Indonesia.",
      B: "Peserta didik mampu menunjukkan pemahaman dan menerapkan nilai-nilai Pancasila dalam kehidupan sehari-hari di lingkungan keluarga, sekolah, dan masyarakat. Peserta didik mampu menunjukkan perilaku yang mencerminkan sikap beriman dan bertakwa kepada Tuhan Yang Maha Esa, berakhlak mulia, berkebinekaan global, bergotong royong, mandiri, bernalar kritis, dan kreatif.",
      C: "Peserta didik mampu menunjukkan pemahaman dan menerapkan nilai-nilai Pancasila dalam kehidupan sehari-hari di lingkungan keluarga, sekolah, dan masyarakat. Peserta didik mampu menunjukkan perilaku yang mencerminkan sikap beriman dan bertakwa kepada Tuhan Yang Maha Esa, berakhlak mulia, berkebinekaan global, bergotong royong, mandiri, bernalar kritis, dan kreatif. Peserta didik mampu memahami hak dan kewajiban sebagai warga negara Indonesia serta menunjukkan rasa cinta tanah air.",
    },
    "Seni dan Budaya": {
      A: "Peserta didik mampu menunjukkan rasa ingin tahu dan menghargai karya seni dan budaya sebagai anugerah Tuhan Yang Maha Esa dan produk budaya masyarakat. Peserta didik mampu mengeksplorasi dan mengekspresikan gagasan dan perasaan melalui karya seni. Peserta didik mampu menampilkan karya seni di depan orang lain.",
      B: "Peserta didik mampu menunjukkan rasa bangga terhadap karya seni dan budaya Indonesia serta menghargai keragaman karya seni dan budaya sebagai anugerah Tuhan Yang Maha Esa dan produk budaya masyarakat. Peserta didik mampu mengeksplorasi, mengekspresikan dan mengomunikasikan gagasan, perasaan dan pengalaman melalui karya seni. Peserta didik mampu menampilkan karya seni di depan orang lain dengan percaya diri.",
      C: "Peserta didik mampu menunjukkan rasa bangga terhadap karya seni dan budaya Indonesia serta menghargai keragaman karya seni dan budaya sebagai anugerah Tuhan Yang Maha Esa dan produk budaya masyarakat. Peserta didik mampu mengeksplorasi, mengekspresikan dan mengomunikasikan gagasan, perasaan dan pengalaman melalui karya seni. Peserta didik mampu menampilkan karya seni di depan orang lain dengan percaya diri dan menunjukkan sikap menghargai karya orang lain.",
    },
    "Pendidikan Jasmani": {
      A: "Peserta didik mampu melakukan aktivitas gerak dasar lokomotor, non-lokomotor, dan manipulatif dalam berbagai bentuk permainan sederhana dan tradisional. Peserta didik mampu memahami pentingnya menjaga kebersihan diri dan lingkungan, serta menerapkan pola hidup sehat dalam kehidupan sehari-hari.",
      B: "Peserta didik mampu melakukan kombinasi gerak dasar lokomotor, non-lokomotor, dan manipulatif dengan koordinasi yang baik dalam berbagai bentuk permainan dan olahraga. Peserta didik mampu memahami dan menerapkan pola hidup sehat, aktivitas fisik, dan gizi seimbang untuk mendukung pertumbuhan dan perkembangan.",
      C: "Peserta didik mampu melakukan kombinasi gerak dasar lokomotor, non-lokomotor, dan manipulatif dengan koordinasi yang baik dalam berbagai bentuk permainan dan olahraga. Peserta didik mampu memahami dan menerapkan pola hidup sehat, aktivitas fisik, dan gizi seimbang untuk mendukung pertumbuhan dan perkembangan. Peserta didik mampu menunjukkan perilaku sportif, jujur, disiplin, bertanggung jawab, dan kerja sama dalam aktivitas fisik.",
    },
    "Bahasa Inggris": {
      A: "Peserta didik mampu menggunakan tindak tutur untuk berinteraksi dalam konteks kelas dan sekolah yang sangat familiar menggunakan bahasa Inggris sederhana. Peserta didik mampu memahami makna dalam teks lisan dan tulis yang sangat sederhana. Peserta didik menunjukkan kesadaran akan adanya perbedaan cara berkomunikasi berdasarkan hubungan sosial, konteks, dan budaya.",
      B: "Peserta didik mampu menggunakan tindak tutur untuk berinteraksi dalam konteks yang familiar dan rutin menggunakan bahasa Inggris sederhana. Peserta didik mampu memahami makna dalam teks lisan dan tulis yang sederhana. Peserta didik mampu memproduksi teks lisan dan tulis yang sederhana. Peserta didik menunjukkan kesadaran akan adanya perbedaan cara berkomunikasi berdasarkan hubungan sosial, konteks, dan budaya.",
      C: "Peserta didik mampu menggunakan tindak tutur untuk berinteraksi dalam konteks yang familiar menggunakan bahasa Inggris sederhana. Peserta didik mampu memahami makna dalam teks lisan dan tulis yang sederhana. Peserta didik mampu memproduksi teks lisan dan tulis yang sederhana dengan struktur yang tepat. Peserta didik menunjukkan kesadaran akan adanya perbedaan cara berkomunikasi berdasarkan hubungan sosial, konteks, dan budaya serta dapat beradaptasi secara sederhana.",
    },
  }

  return cpData[mataPelajaran]?.[fase] || "Capaian Pembelajaran belum tersedia untuk mata pelajaran dan fase ini."
}
